### ISSUE TITLE
[BUG] ChatEx newest Version only one Letter of the Player in Tablist

### ISSUE THREAD

**Issue by ShokeStreamer** [TheJeterLP/ChatEx#46]
**Describe the bug**
PermissionEx and ChatEx and Vault using to get prefix in my tablist
with the newest Version of ChatEx the Prefix will be displayed but also only the first Letter of the Player.

**To Reproduce**
PermissionEx
ChatEx 2.7.0

**Expected behavior**
Should display Username

**Please complete the following information:**
 - OS: WINDOWS
 - Java Version i dont know
 - Minecraft Version 1.16.5
 - ChatEx Version 2.7.0

**Files (please complete the following information):**
///////////////
**Additional context**
//////////////

FIXXED by installing lower Version

**Comment by worldOneo** [comment]
@TheJeterLP
Propably due to [PR#45](https://github.com/TheJeterLP/ChatEx/pull/45/files#diff-917b87caddbcac2376814b9b932a72957f0d45f3d0a1f02e7b5abddf5a85f6c7R44)
The issue which reported this was in the mc-version 1.7 the easiest fix for that problem is to deprecate 1.7 as it should be.
I tested the prefix stuff, and even in 1.8.8 there doesnt seem to be a problem with 17+ characters.

**Comment by TheJeterLP** [comment]
Alright thanks, I'll fix it rn
